import { Product } from '../models/product.model';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Ethiopia Yirgacheffe',
    description: 'A luminous washed single-origin from the Gedeo Zone. Jasmine, ripe stone fruit, and bergamot unfold across a silky body with a clean tea-like finish — the definitive East African cup.',
    price: 1950,
    origin: 'Ethiopia',
    roastLevel: 'light',
    flavorNotes: ['Jasmine', 'Stone Fruit', 'Bergamot', 'Honey'],
    imageUrl: 'ethiopia-yirgacheffe',
    stock: 48,
    rating: 4.5,
    category: 'single-origin',
    process: 'washed',
    altitude: '1,800–2,200m',
  },
  {
    id: 2,
    name: 'Colombia Huila Supremo',
    description: 'Grown on steep Andean slopes in Huila, this washed coffee balances caramel sweetness with red apple brightness. A versatile crowd-pleaser that works beautifully as both filter and espresso.',
    price: 1750,
    origin: 'Colombia',
    roastLevel: 'medium',
    flavorNotes: ['Caramel', 'Red Apple', 'Milk Chocolate', 'Citrus'],
    imageUrl: 'colombia-huila',
    stock: 72,
    rating: 4.0,
    category: 'single-origin',
    process: 'washed',
    altitude: '1,500–2,000m',
  },
  {
    id: 3,
    name: 'Kenya Nyeri AA',
    description: 'The classic Kenyan profile at its apex: blackcurrant, grapefruit zest, and a savoury tomato-leaf undertone. Juicy acidity and a heavy, coating mouthfeel make this a pour-over essential.',
    price: 2150,
    origin: 'Kenya',
    roastLevel: 'light',
    flavorNotes: ['Blackcurrant', 'Grapefruit', 'Tomato Leaf', 'Brown Sugar'],
    imageUrl: 'kenya-nyeri',
    stock: 36,
    rating: 4.5,
    category: 'single-origin',
    process: 'washed',
    altitude: '1,600–2,100m',
  },
  {
    id: 4,
    name: 'Guatemala Antigua',
    description: 'Volcanic soil from the Antigua valley imparts a distinctive depth: dark chocolate, roasted almond, and subtle baking spice. Full-bodied and comforting, ideal for a French press ritual.',
    price: 1850,
    origin: 'Guatemala',
    roastLevel: 'medium',
    flavorNotes: ['Dark Chocolate', 'Roasted Almond', 'Baking Spice', 'Toffee'],
    imageUrl: 'guatemala-antigua',
    stock: 54,
    rating: 4.0,
    category: 'single-origin',
    process: 'washed',
    altitude: '1,500–1,700m',
  },
  {
    id: 5,
    name: 'Sumatra Mandheling',
    description: 'Wet-hulled in the traditional Sumatran style, this coffee delivers profound earthiness: cedar, dark cocoa, and a whisper of tobacco smoke. Low acidity, immense body — a dark-roast aficionado\'s grail.',
    price: 2050,
    origin: 'Indonesia',
    roastLevel: 'dark',
    flavorNotes: ['Cedar', 'Dark Cocoa', 'Tobacco', 'Earth'],
    imageUrl: 'sumatra-mandheling',
    stock: 40,
    rating: 4.0,
    category: 'single-origin',
    process: 'wet-hulled',
    altitude: '900–1,500m',
  },
  {
    id: 6,
    name: 'Costa Rica Tarrazú',
    description: 'Honey-processed on a family micro-mill in Tarrazú. Orange blossom, panela sugar, and a hint of passionfruit create a radiant, clean cup with crystalline clarity.',
    price: 1950,
    origin: 'Costa Rica',
    roastLevel: 'light',
    flavorNotes: ['Orange Blossom', 'Panela', 'Passionfruit', 'Vanilla'],
    imageUrl: 'costa-rica-tarrazu',
    stock: 30,
    rating: 4.5,
    category: 'single-origin',
    process: 'honey',
    altitude: '1,400–1,900m',
  },
  {
    id: 7,
    name: 'Brazil Cerrado Natural',
    description: 'Sun-dried on raised beds in the Cerrado savanna, this natural-process coffee bursts with chocolate-covered blueberry, hazelnut praline, and a creamy body that lingers.',
    price: 1650,
    origin: 'Brazil',
    roastLevel: 'medium',
    flavorNotes: ['Chocolate', 'Blueberry', 'Hazelnut', 'Praline'],
    imageUrl: 'brazil-cerrado',
    stock: 60,
    rating: 4.0,
    category: 'single-origin',
    process: 'natural',
    altitude: '900–1,200m',
  },
  {
    id: 8,
    name: 'Rwanda Nyamasheke',
    description: 'From the high-altitude washing stations of Lake Kivu\'s shore. Pink grapefruit, black tea, and a delicate floral nose give way to a long, resonant finish.',
    price: 1950,
    origin: 'Rwanda',
    roastLevel: 'light',
    flavorNotes: ['Pink Grapefruit', 'Black Tea', 'Floral', 'Lemon'],
    imageUrl: 'rwanda-nyamasheke',
    stock: 28,
    rating: 4.5,
    category: 'single-origin',
    process: 'washed',
    altitude: '1,700–2,200m',
  },
  {
    id: 9,
    name: 'Midnight Velvet Blend',
    description: 'Our house dark-roast blend, built for espresso. Three origins combine for a syrupy shot of bittersweet chocolate, toasted marshmallow, and a wisp of smokiness — magnificent with milk.',
    price: 1700,
    origin: 'Blend',
    roastLevel: 'dark',
    flavorNotes: ['Bittersweet Chocolate', 'Toasted Marshmallow', 'Smoke', 'Molasses'],
    imageUrl: 'midnight-velvet',
    stock: 90,
    rating: 4.0,
    category: 'blend',
    process: 'blend',
    altitude: 'Various',
  },
  {
    id: 10,
    name: 'Daybreak Seasonal Blend',
    description: 'A rotating composition of the season\'s finest light roasts. Current profile: Ethiopian florals meet Colombian caramel for a bright, approachable everyday cup.',
    price: 1800,
    origin: 'Blend',
    roastLevel: 'light',
    flavorNotes: ['Floral', 'Caramel', 'Citrus', 'Vanilla'],
    imageUrl: 'daybreak-blend',
    stock: 65,
    rating: 4.0,
    category: 'blend',
    process: 'blend',
    altitude: 'Various',
  },
  {
    id: 11,
    name: 'Peru Cajamarca Organic',
    description: 'Certified organic from a cooperative of smallholder farmers in Cajamarca. Smooth milk chocolate, gentle citrus, and a nutty finish — an easy-drinking crowd-pleaser.',
    price: 1800,
    origin: 'Peru',
    roastLevel: 'medium',
    flavorNotes: ['Milk Chocolate', 'Citrus', 'Almond', 'Brown Sugar'],
    imageUrl: 'peru-cajamarca',
    stock: 45,
    rating: 4.0,
    category: 'single-origin',
    process: 'washed',
    altitude: '1,300–1,800m',
  },
  {
    id: 12,
    name: 'Honduras Marcala',
    description: 'Anaerobic-fermented for 72 hours before drying, this experimental lot from Marcala pushes boundaries. Intense tropical fruit, cacao nib, and a sparkling acidity — unlike anything in the lineup.',
    price: 2250,
    origin: 'Honduras',
    roastLevel: 'light',
    flavorNotes: ['Tropical Fruit', 'Cacao Nib', 'Sparkling', 'Cinnamon'],
    imageUrl: 'honduras-marcala',
    stock: 20,
    rating: 5.0,
    category: 'single-origin',
    process: 'anaerobic',
    altitude: '1,400–1,700m',
  },
  {
    id: 13,
    name: 'Decaf Swiss Water',
    description: 'Chemical-free Swiss Water Process decaf from a single estate in Chiapas. Retains remarkable origin character: caramel, green apple, and a clean finish without the caffeine.',
    price: 1850,
    origin: 'Mexico',
    roastLevel: 'medium',
    flavorNotes: ['Caramel', 'Green Apple', 'Clean', 'Nutmeg'],
    imageUrl: 'decaf-swiss-water',
    stock: 35,
    rating: 3.5,
    category: 'decaf',
    process: 'washed',
    altitude: '1,100–1,500m',
  },
  {
    id: 14,
    name: 'Espresso Forte',
    description: 'Purpose-built for the espresso machine. A calibrated roast of Brazilian natural and Guatemalan washed beans: thick crema, dark toffee, and a hint of dried cherry.',
    price: 1750,
    origin: 'Blend',
    roastLevel: 'dark',
    flavorNotes: ['Dark Toffee', 'Dried Cherry', 'Cocoa Powder', 'Roasted Nuts'],
    imageUrl: 'espresso-forte',
    stock: 80,
    rating: 4.0,
    category: 'espresso',
    process: 'blend',
    altitude: 'Various',
  },
  {
    id: 15,
    name: 'Panama Geisha',
    description: 'The legendary Geisha varietal from the highlands of Boquete. Exquisite jasmine florals, ripe mango, and a bergamot lift define this competition-grade lot — a once-in-a-season experience.',
    price: 4200,
    origin: 'Panama',
    roastLevel: 'light',
    flavorNotes: ['Jasmine', 'Mango', 'Bergamot', 'Honeysuckle'],
    imageUrl: 'panama-geisha',
    stock: 12,
    rating: 5.0,
    category: 'single-origin',
    process: 'washed',
    altitude: '1,600–1,900m',
  },
  {
    id: 16,
    name: 'Burundi Kayanza',
    description: 'Double-washed in the highlands of Kayanza province. Pomegranate, black tea, and a subtle spice complexity yield a cup of remarkable structure and elegance.',
    price: 1950,
    origin: 'Burundi',
    roastLevel: 'light',
    flavorNotes: ['Pomegranate', 'Black Tea', 'Allspice', 'Hibiscus'],
    imageUrl: 'burundi-kayanza',
    stock: 24,
    rating: 4.0,
    category: 'single-origin',
    process: 'washed',
    altitude: '1,700–2,000m',
  },
];
